mindmap
  root((Ed Guest))
    ((BLEXIT <br>SQUAD)
      Vikta Harvey
      Marek Paprota

    ((LIGHTSON)
      Rudolf Benadie
      Joao Simoes
      Bons Ralph
      Chris Stack
      Jorge Loureiro
      Pauline Wangunyu

  

    ((WEBEO)
      Tony Panczenko
      Blaze Lalowicz
      Ricardo Sacramento
      Tim Balestrini
      Dimitrios Antonaras
      Emma Waugh
   
    ((WHIZEO<BR>CHAT)
      Dominik Potera
      Krzysztof Babendych
      Francisco Rosa

    ((ENABLING)
      Daryl Lyons
      James Yao
      Alvin Nilsson
      
    ((Manager(
      Pete Reeves
      Mark Shepherd
      Stuart Mackenzie<br>Scrum Master
      Adam Drew<br> Architect

    ((RUN)
      Rudolf Benadie
      Thomas Hill
      Raquel Bermejo
      Isaac Mulcahy
      Matt Woodroffe
      Junaid Mahmood

    ((BUILD)
        Ethan Stoffel
        Neha Tak
        Qi Ning