mindmap
  root((Engineering )
    )Run Team(
        ))Rudolf ((
      Vikta
      Dimitrios
      Matt
      James
      )Build(
        Junaid
        Ethan
        Neha 

    )Portal Squad(
        ))Raquel((
      (Pete)
      Joao
      Bons
    )Integration <br>Squad(
        ))Thomas((
        
      (Pete)
      Jorge
      Pauline
      (Mel)
      
    )Webeo<br> Squad(
        ))Tony((
        
      Blaze
      Isaac
      Ricardo
      Tim
      (Mike Terry<br>PO)
    )Whizeo <br>Chat <br>Squad(
        ))Mark((
        
      Marek
      Dominik
      Krzysztof
      Francisco
    )Enabling(
        ))Daryl((
      Oliver
      Chris
    )QA(
      Emma
      Neha
      Tim
    )Engineering<br>Managers(
      ))Ed Guest<br>VP((
      Pete
      Mark
      Stuart<br>Scrum Master
      Adam<br>Architect
