mindmap
  root((Engineering )
    )Run Team(
        ))Rudolf ((
      Vikta
      Dimitrios
      Matt
      James
      )Build(
        Junaid
        Ethan
        Neha 

    )Portal Squad(
        ))Raquel((
      (Mike Terry<br>PM)
      Joao
      Bons
    )Integration <br>Squad(
        ))Thomas((
        
      Jorge
      Pauline
      (Mel PO)
      
    )Webeo<br> Squad(
        ))Tony((
      (Liam <br> PM)  
      Blaze
      Isaac
      Ricardo
      Tim
   
    )Whizeo <br>Chat <br>Squad(
        ))Mark((
      
      (Liam PM)
      Marek
      Dominik
      Krzysztof
      Francisco
    )Enabling(
        ))Daryl((
      Oliver
      Chris
    )QA(
      Emma
      Neha
      Tim
    )Engineering<br>Managers(
      ))Ed Guest<br>VP((
      Pete
      Mark
      Stuart<br>Scrum Master
      Adam<br> Architect
