C4Context
      title System Context diagram Integrations
      ComponentQueue(visitFeed, "Visit Feed")
      Rel(visitFeed, visitIngress, "sends")
      System_Boundary(TyphoonSys, "Typhoon system"){
        Component(visitIngress, "Visit ingress")
        Component(visitIngress2, "")
        
        ComponentQueue(visitReadyTopic, "Visit ready topic")
        Rel(visitIngress, visitReadyTopic, "When ready")

        System_Boundary(intTyphoon, "Integration Typhoon mono repo"){
          Component(mrVisitHandler, "visithandler")
          Component(mrsteps, "step logic handler")
          Rel(mrOrch, mrsteps, "")
          Component(mrOrch, "orchestrator")
            Rel(mrVisitHandler, mrOrch, "")
          Component(mrDLQ, "DLQ processor")
            
          
          Component(mrauth, "auth handler")
          Rel(mrOrch, mrauth, "uses")

          
        }
        
        
        Component(legVisitHandler, "Legacy visithandler")
        Rel(visitReadyTopic, mrVisitHandler, "reads (feature flag)")
        Rel(visitReadyTopic, legVisitHandler, "reads (feature flag)")
      }

     

      System_Boundary(s0, ""){
        Component(customjobs, "Custom jobs")
        Component(logicApps, "Logic apps AZURE")
        Component(blendr, "Blendr")

        Rel(legVisitHandler, customjobs, "send")
        Rel(legVisitHandler, logicApps, "send")
        Rel(legVisitHandler, blendr, "send")
        }

 System_Boundary(dbs, "databases"){
        ComponentDb(webinsightsDb, "Webinsights SQL")
        ComponentDb(webForensicsDb, "Webforensics SQL")
        Rel(mrOrch, webinsightsDb, "uses")
        Rel(mrOrch, webForensicsDb, "uses")
      }